"""Fragment 13_save_all_api_keys.py. Loaded into the main module namespace."""
def save_all_api_keys(amass_keys: Dict[str, str], subfinder_keys: Dict[str, str]) -> Tuple[bool, str]:
    """Save API keys to both Amass and Subfinder configs."""
    amass_success, amass_msg = write_amass_api_keys(amass_keys)
    subfinder_success, subfinder_msg = write_subfinder_api_keys(subfinder_keys)
    
    if amass_success and subfinder_success:
        return True, "API keys saved successfully"
    elif amass_success:
        return False, f"Amass keys saved, but Subfinder failed: {subfinder_msg}"
    elif subfinder_success:
        return False, f"Subfinder keys saved, but Amass failed: {amass_msg}"
    else:
        return False, f"Failed to save keys. Amass: {amass_msg}, Subfinder: {subfinder_msg}"


# ================== AMASS CONFIG ==================

def ensure_amass_config_interactive() -> None:
    """
    If no amass config is found, optionally ask user if they want a basic template
    and (optionally) enter some keys.
    NOTE: This is only called during pipeline execution if setup was not completed.
    The main setup wizard handles this during first run.
    """
    # Check if setup was completed - if so, don't block with interactive prompts
    cfg = get_config()
    if cfg.get("setup_completed", False):
        # Setup was completed, don't prompt during execution
        config_dir = Path.home() / ".config" / "amass"
        config_file = config_dir / "config.ini"
        if not config_file.exists():
            log("Amass config not found, but setup was completed. Skipping interactive prompt.")
            log("You can configure Amass API keys later through the web UI or by editing ~/.config/amass/config.ini")
        return
    
    config_dir = Path.home() / ".config" / "amass"
    config_file = config_dir / "config.ini"

    if config_file.exists():
        return

    if not sys.stdin.isatty():
        log("No Amass config.ini found and running non-interactively; skipping auto setup.")
        return

    log("No Amass config.ini found (~/.config/amass/config.ini).")
    try:
        ans = input("Do you want to generate a basic Amass config and optionally enter API keys? [y/N]: ").strip().lower()
    except EOFError:
        # Non-interactive case, just skip
        return

    if ans != "y":
        log("Skipping Amass API key setup.")
        return

    config_dir.mkdir(parents=True, exist_ok=True)

    # Ask optionally for some keys
    providers = {
        "shodan": None,
        "virustotal": None,
        "securitytrails": None,
        "censys": None,
        "passivetotal": None,
    }

    log("Press Enter to skip any provider.")
    for name in list(providers.keys()):
        try:
            key = input(f"Enter API key for {name} (or leave blank): ").strip()
        except EOFError:
            key = ""
        providers[name] = key or None

    # Write basic config.ini
    lines = [
        "# Generated by recon_dashboard.py",
        "[resolvers]",
        "dns = 8.8.8.8, 1.1.1.1",
        "",
        "[datasources]",
    ]
    for name, key in providers.items():
        if key:
            lines.append(f"    [{name}]")
            lines.append(f"    apikey = {key}")
            lines.append("")
        else:
            # add commented stub
            lines.append(f"    #[{name}]")
            lines.append("    #apikey = YOUR_KEY_HERE")
            lines.append("")

    atomic_write_text(config_file, "\n".join(lines))
    log(f"Amass config created at {config_file}. You can tweak it later if needed.")


# ================== PIPELINE STEPS ==================

def run_subprocess(
    cmd,
    outfile: Optional[Path] = None,
    *,
    job_domain: Optional[str] = None,
    step: Optional[str] = None,
    env: Optional[Dict[str, str]] = None,
    timeout: Optional[int] = None,
) -> bool:
    # Apply global rate limiting before running any tool
    apply_rate_limit()
    
    display_cmd = " ".join(cmd)
    log(f"Running: {display_cmd}")
    if job_domain:
        job_pause_point(job_domain)
    if job_domain:
        job_log_append(job_domain, f"$ {display_cmd}", source=step or "command")
    try:
        merged_env = os.environ.copy()
        
        # Set environment variables to prevent interactive prompts from various tools
        # These ensure tools run in non-interactive mode and don't freeze waiting for input
        non_interactive_env = {
            # General non-interactive settings
            "DEBIAN_FRONTEND": "noninteractive",
            "TERM": "dumb",
            "CI": "true",  # Many tools detect CI environments and disable interactive features
            
            # Subfinder - prevent interactive config creation
            "SUBFINDER_CONFIG_PATH": str(Path.home() / ".config" / "subfinder" / "provider-config.yaml"),
            
            # Nuclei - prevent interactive prompts and template updates
            "NUCLEI_NONINTERACTIVE": "1",
            "NUCLEI_NO_COLOR": "1",
            
            # Amass - already handled via config file but ensure non-interactive
            "AMASS_CONFIG": str(Path.home() / ".config" / "amass" / "config.ini"),
            
            # GitHub CLI / github-subdomains - prevent auth prompts
            "GH_NO_UPDATE_NOTIFIER": "1",
            "GH_PAGER": "",
            
            # General tool settings to prevent prompts
            "PAGER": "",
            "MANPAGER": "",
            "NO_COLOR": "1",
        }
        
        # Apply non-interactive environment
        merged_env.update(non_interactive_env)
        
        # Apply any custom environment variables passed in
        if env:
            merged_env.update({k: str(v) for k, v in env.items()})

        result = subprocess.run(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=False,
            env=merged_env,
            timeout=timeout,
            stdin=subprocess.DEVNULL,  # Prevent reading from stdin - critical for non-interactive mode
        )

        stdout = result.stdout or ""
        stderr = result.stderr or ""

        if outfile:
            try:
                with open(outfile, "w", encoding="utf-8") as f:
                    f.write(stdout)
            except Exception as file_err:
                log(f"Error writing {outfile}: {file_err}")

        if job_domain:
            if stdout.strip():
                job_log_append(job_domain, stdout, source=step or cmd[0])
            if stderr.strip():
                job_log_append(job_domain, stderr, source=f"{(step or cmd[0]).upper()} stderr")

        if result.returncode != 0:
            stderr_preview = (stderr or "")[:500]
            log(
                f"Command failed (return code {result.returncode}): "
                + display_cmd
                + "\nstderr: " + stderr_preview
            )
            
            # Check if stderr contains rate limit indicators and track them
            combined_output = stdout + stderr
            if any(keyword in combined_output.lower() for keyword in 
                   ["rate limit", "too many requests", "429", "throttle", "slow down"]):
                if job_domain:
                    track_timeout_error(job_domain, Exception(stderr_preview), job_domain)
            
            return False

    except subprocess.TimeoutExpired as e:
        log(f"Command timeout: {display_cmd}")
        if job_domain:
            job_log_append(job_domain, f"Command timeout after {timeout}s", source=step or "system")
            # Track timeout errors
            track_timeout_error(job_domain, e, job_domain)
        return False

    except FileNotFoundError:
        log(f"Command not found: {cmd[0]}")
        if job_domain:
            job_log_append(job_domain, f"Command not found: {cmd[0]}", source=step or "system")
        return False

    except Exception as e:
        log("Error running command " + display_cmd + f": {e}")
        if job_domain:
            job_log_append(job_domain, f"Error: {e}", source=step or "system")
            # Track potential rate limit errors
            track_timeout_error(job_domain, e, job_domain)
        return False

    return True


def amass_enum(domain: str, config: Optional[Dict[str, Any]] = None, job_domain: Optional[str] = None) -> Path:
    """
    Run Amass enum with JSON output and return path to JSON file.
    """
    if not ensure_tool_installed("amass"):
        return None

    ensure_amass_config_interactive()

    out_base = DATA_DIR / f"amass_{domain}"
    out_json = out_base.with_suffix(".json")
    extra_args = []
    timeout = None
    cfg = config if config is not None else get_config()
    try:
        timeout = int(cfg.get("amass_timeout"))
        if timeout <= 0:
            timeout = None
    except (TypeError, ValueError):
        timeout = None
    if cfg.get("amass_passive"):
        extra_args.append("-passive")
    resolvers = _normalize_resolver_list(cfg.get("dns_resolvers"))
    if resolvers:
        rf = write_resolvers_file(resolvers)
        extra_args.extend(["-rf", str(rf)])
        for resolver in resolvers:
            extra_args.extend(["-r", resolver])
        if job_domain:
            job_log_append(job_domain, f"Amass DNS resolvers: {', '.join(resolvers)}", "amass")
    cmd = [
        TOOLS["amass"],
        "enum",
        "-d", domain,
        "-oA", str(out_base),
    ] + extra_args

    context = {
        "DOMAIN": domain,
        "OUTPUT_PREFIX": str(out_base),
        "OUTPUT_JSON": str(out_json),
    }
    cmd = apply_template_flags("amass", cmd, context, config)
    success = run_subprocess(cmd, job_domain=job_domain, step="amass", timeout=timeout)
    return out_json if success and out_json.exists() else None


def parse_amass_json(json_path: Path) -> List[str]:
    subs = set()
    if not json_path or not json_path.exists():
        return []
    try:
        with open(json_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    obj = json.loads(line)
                    name = obj.get("name")
                    if name:
                        subs.add(name.strip().lower())
                except Exception:
                    continue
    except Exception as e:
        log(f"Error parsing Amass JSON: {e}")
    return sorted(subs)


def strip_ansi_codes(text: str) -> str:
    """
    Remove ANSI escape sequences (color codes, formatting) from text.
    This handles common terminal color codes that tools like sublist3r add to output.
    """
    # Pattern matches ANSI escape sequences including CSI sequences
    # \x1b is ESC (hex), \033 is ESC (octal)
    # Matches standard ANSI control sequences ending in A-Za-z
    ansi_escape = re.compile(r'\x1b\[[0-9;]*[A-Za-z]|\033\[[0-9;]*[A-Za-z]')
    return ansi_escape.sub('', text)


def is_valid_subdomain(text: str) -> bool:
    """
    Validate that a string looks like a valid domain or subdomain.
    Returns False for ANSI codes, error messages, status messages, wildcards, etc.
    
    NOTE: This function is used to validate tool output (discovered subdomains).
    Wildcards are rejected here because tools should return concrete subdomains,
    not wildcard patterns. Wildcard inputs are handled separately by expand_wildcard_targets().
    """
    if not text:
        return False
    
    # Strip ANSI codes first
    cleaned = strip_ansi_codes(text).strip()
    if not cleaned:
        return False
    
    # Reject wildcards - these should not appear in tool output
    # Wildcard DNS records like *.api.example.com should be ignored
    if '*' in cleaned:
        return False
    
    # Reject lines that are clearly not domains
    # Check for common patterns in tool output that shouldn't be domains
    invalid_patterns = [
        r'^\[',  # Starts with bracket (ANSI remnants, arrays, etc.)
        r'^\]',  # Starts with closing bracket
        r'^[-\+#]',  # Starts with status symbols
        r'error|Error|ERROR',  # Contains error keywords
        r'warning|Warning|WARNING',  # Contains warning keywords
        r'searching|enumerat|finish|coded by',  # Tool status messages
        r'^\s*$',  # Empty or whitespace only
        r'\s{2,}',  # Multiple consecutive spaces (likely formatted output)
        r'^[0-9]+\s',  # Starts with number and space (table rows)
        r'^\||^-+$|^\++$',  # Table borders
        r'^http://|^https://',  # URLs (not raw domains)
        r'[ \t\r\n\f\v]',  # Contains ASCII whitespace (domains don't have spaces)
    ]
    
    for pattern in invalid_patterns:
        if re.search(pattern, cleaned, re.IGNORECASE):
            return False
    
    # Basic domain validation: should contain at least one dot and valid chars
    # Valid domain characters: alphanumeric, dots, hyphens, underscores
    # Must contain at least one dot (subdomain.domain or domain.tld)
    if '.' not in cleaned:
        return False
    
    # Check if it looks like a domain (alphanumeric with dots, hyphens, underscores)
    # No wildcards allowed in tool output
    domain_pattern = r'^[a-z0-9]([a-z0-9\-_]*[a-z0-9])?(\.[a-z0-9]([a-z0-9\-_]*[a-z0-9])?)+$'
    if not re.match(domain_pattern, cleaned, re.IGNORECASE):
        return False
    
    return True


def read_lines_file(path: Path) -> List[str]:
    if not path or not path.exists():
        return []
    lines = []
    try:
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    # Strip ANSI codes and validate
                    cleaned = strip_ansi_codes(line).strip()
                    if cleaned and is_valid_subdomain(cleaned):
                        lines.append(cleaned.lower())
    except Exception as exc:
        log(f"Error reading {path}: {exc}")
    return lines


def amass_collect_subdomains(domain: str, config: Optional[Dict[str, Any]] = None, job_domain: Optional[str] = None) -> List[str]:
    amass_json = amass_enum(domain, config=config, job_domain=job_domain)
    return parse_amass_json(amass_json)


def subfinder_enum(domain: str, config: Optional[Dict[str, Any]] = None, job_domain: Optional[str] = None) -> List[str]:
    if not ensure_tool_installed("subfinder"):
        return []
    out_path = DATA_DIR / f"subfinder_{domain}.txt"
    threads = 32
    if config:
        try:
            threads = max(1, int(config.get("subfinder_threads", threads)))
        except (TypeError, ValueError):
            threads = 32
    cmd = [
        TOOLS["subfinder"],
        "-silent",
        "-d", domain,
        "-t", str(threads),
        "-o", str(out_path),
    ]
    context = {
        "DOMAIN": domain,
        "OUTPUT": str(out_path),
        "THREADS": threads,
    }
    cmd = apply_template_flags("subfinder", cmd, context, config)
    success = run_subprocess(cmd, outfile=out_path, job_domain=job_domain, step="subfinder")
    return read_lines_file(out_path) if success else []


def assetfinder_enum(domain: str, config: Optional[Dict[str, Any]] = None, job_domain: Optional[str] = None) -> List[str]:
    if not ensure_tool_installed("assetfinder"):
        return []
    out_path = DATA_DIR / f"assetfinder_{domain}.txt"
    threads = 10
    if config:
        try:
            threads = max(1, int(config.get("assetfinder_threads", threads)))
        except (TypeError, ValueError):
            threads = 10
    cmd = [
        TOOLS["assetfinder"],
        "--subs-only",
        domain,
    ]
    context = {
        "DOMAIN": domain,
        "OUTPUT": str(out_path),
        "THREADS": threads,
    }
    cmd = apply_template_flags("assetfinder", cmd, context, config)
    success = run_subprocess(
        cmd,
        outfile=out_path,
        job_domain=job_domain,
        step="assetfinder",
        env={"GOMAXPROCS": str(threads)},
    )
    return read_lines_file(out_path) if success else []
